### ISSUE TITLE
Can only add one date. 

### ISSUE THREAD

**Issue by paulneibarger** [daskeyboard/daskeyboard-applet--birthday-reminder#21]
The description states: "This applet will remind you of the birthday dates you don't want to forget." I can only add a single date to the applet.

**Comment by supercobra** [comment]
Good suggestion.

**Comment by paulneibarger** [comment]
I looked at the code, this isn't a bug as I suspected. I may fork it and contribute to it. I like how the Q game deals adds a + button that apprears to add it to a list. I'll play around and see what I can do.

**Comment by fabiendv** [comment]
I am going to close this issue. 
Let us know if you need help with your fork. We'd be glad to have one more contributor :+1:
